# Generated by Django 4.2.6 on 2023-10-13 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=15000, unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=150)),
                ("content", models.TextField(blank=True)),
                ("cover_photo", models.ImageField(upload_to="cover_photos")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Technology", "Technology"),
                            ("Travel", "Travel"),
                            ("Food", "Food"),
                            ("Lifestyle", "Lifestyle"),
                            ("Fitness", "Fitness"),
                            ("Entertainment", "Entertainment"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
