# Generated by Django 4.2.6 on 2023-10-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_post_cover_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cover_photo",
            field=models.ImageField(blank=True, null=True, upload_to="cover_photos/"),
        ),
    ]
